# Generated by Django 3.1.4 on 2021-01-01 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
