# Generated by Django 3.1.4 on 2021-01-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksApp', '0003_auto_20210102_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
